name = "shadowdark"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "shadowdark"
# Replace with real database_id after running: wrangler d1 create shadowdark
database_id = "188b0899-9eae-43b2-9c47-48cc6a5e1092"
