name = "shadowdark"
main = ".open-next/worker.js"
account_id = "4bef1453ad78da6e3bb7e83b421e26df"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "shadowdark"
# Replace with real database_id after running: wrangler d1 create shadowdark
database_id = "aae22728-e098-4c3e-811e-aa1c73d33fbb"
