CREATE TABLE IF NOT EXISTS characters (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  pronouns TEXT NOT NULL DEFAULT 'they/them',
  ancestry TEXT NOT NULL,
  class TEXT NOT NULL,
  level INTEGER NOT NULL DEFAULT 1,
  xp INTEGER NOT NULL DEFAULT 0,
  alignment TEXT NOT NULL,
  background TEXT NOT NULL,
  str INTEGER NOT NULL DEFAULT 10,
  dex INTEGER NOT NULL DEFAULT 10,
  con INTEGER NOT NULL DEFAULT 10,
  int INTEGER NOT NULL DEFAULT 10,
  wis INTEGER NOT NULL DEFAULT 10,
  cha INTEGER NOT NULL DEFAULT 10,
  hp INTEGER NOT NULL DEFAULT 1,
  max_hp INTEGER NOT NULL DEFAULT 1,
  ac INTEGER NOT NULL DEFAULT 10,
  equipment TEXT NOT NULL DEFAULT '[]',
  spells TEXT NOT NULL DEFAULT '[]',
  talents TEXT NOT NULL DEFAULT '[]',
  features TEXT NOT NULL DEFAULT '[]',
  gold INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS campaigns (
  id TEXT PRIMARY KEY,
  character_id TEXT NOT NULL REFERENCES characters(id),
  name TEXT NOT NULL,
  state TEXT NOT NULL DEFAULT 'active',
  gm_persona TEXT NOT NULL DEFAULT '',
  world_state TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS sessions (
  id TEXT PRIMARY KEY,
  campaign_id TEXT NOT NULL REFERENCES campaigns(id),
  session_number INTEGER NOT NULL,
  messages TEXT NOT NULL DEFAULT '[]',
  summary TEXT,
  game_state_snapshot TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);