import type { AdventureCollection } from "./types";

export const TEST_GAUNTLET: AdventureCollection = {
  id: "test-gauntlet",
  title: "Test Gauntlet",
  description: "7 oneshot adventures designed to test specific parts of gameplay",
  adventures: [
    {
      id: "the-throat-of-iron",
      title: "The Throat of Iron",
      levelMin: 1,
      levelMax: 3,
      synopsis:
        "A collapsed hillside has exposed the entrance to an Underways vault. Two sellswords camped at the mouth are willing to join anyone bold enough to go in. Inside: a guardian construct, a cursed relic, a trapped corridor, and a sealed inner sanctum where something old is waking up.",
      hook: "A shepherd found a hole in the hillside after last night's storm — worked stone, not natural. Pale light pulses from within. Two sellswords at the local tavern heard the same rumor and are heading there at dawn. They're looking for a third.",
      locations: [
        {
          id: "cave-mouth",
          name: "The Cave Mouth",
          description:
            "A rain-carved opening in the hillside reveals dressed stone behind the mud. Builder glyphs frame an archway. The two sellswords — Briar and Stump — wait here with their packs. Just inside the arch, a 30-foot corridor descends at a steep angle into darkness. Torchlight barely reaches the first landing. IMPORTANT: This is where combat begins. Two root creepers (AC 11, HP 9 each) are coiled in the ceiling shadows and drop on the party as soon as anyone steps past the archway. Run this as a full multi-round combat with initiative. The sellswords fight alongside the player.",
          mapPosition: "Surface level, hillside entrance facing south",
          dimensions: "Archway 10 ft wide × 8 ft tall; descending corridor 30 ft long × 10 ft wide",
          connections: [
            "South: open hillside (exit to surface)",
            "North: descending stone corridor to the Glyph Hall (~30 ft, steep grade)",
          ],
          npcs: [
            "Briar (Human Fighter, AC 13, HP 12, longsword +3, 1d8+1) — laconic, scarred, dependable",
            "Stump (Knocker Rogue, AC 12, HP 8, hunting bow +3, 1d6+1, daggers) — cheerful, talks too much, sharp eyes",
          ],
          hazards: [
            "Root creeper ambush: 2 root creepers (AC 11, HP 9, bite +2, 1d6) drop from ceiling on round 1",
            "Darkness: no natural light past the archway — torches required",
          ],
          hasPcMap: false,
          locationType: "cave",
        },
        {
          id: "glyph-hall",
          name: "The Glyph Hall",
          description:
            "A rectangular chamber with builder glyphs covering every surface. The air hums. A stone pedestal at the center holds a tarnished iron circlet — the Ward of Echoes (cursed: grants +1 to spell checks but adds +2 permanent Toll on first use). A successful INT DC 12 check reads the glyphs as a warning. A locked iron door (DC 14 to pick, DC 16 to force) leads deeper. IMPORTANT: When the circlet is touched, a bound spirit manifests and poses a riddle. Answering correctly opens the iron door without a check. Answering wrong triggers a psychic blast (1d8 damage, WIS DC 12 to halve).",
          mapPosition: "Underground, below the cave mouth — first major chamber",
          dimensions: "40 ft × 30 ft rectangular, 15 ft ceiling",
          connections: [
            "South: ascending corridor to the Cave Mouth (~30 ft)",
            "North: locked iron door to the Trapped Corridor (DC 14 pick / DC 16 force, or answer the riddle)",
          ],
          hazards: [
            "Cursed circlet: Ward of Echoes grants +1 spell checks but +2 permanent Toll on first use",
            "Spirit riddle: wrong answer deals 1d8 psychic damage (WIS DC 12 halves)",
          ],
          locationType: "cave",
        },
        {
          id: "trapped-corridor",
          name: "The Trapped Corridor",
          description:
            "A 60-foot corridor lined with pressure plates and dart tubes. Three sections of trapped floor (DEX DC 12 to cross each; failure deals 1d4 piercing). A character with thieves' tools can disable each trap (DC 13). Stump offers to scout ahead if asked. Halfway down, a small alcove holds a locked chest (DC 11) containing 30 gold and a healing potion.",
          mapPosition: "Underground, connecting the Glyph Hall to the Inner Sanctum",
          dimensions: "60 ft long × 10 ft wide, 10 ft ceiling",
          connections: [
            "South: iron door to the Glyph Hall",
            "North: heavy stone door to the Inner Sanctum (pushes open, not locked)",
          ],
          hazards: [
            "Dart traps: 3 pressure-plate sections, DEX DC 12 each, 1d4 piercing on failure",
            "Disarm: thieves' tools DC 13 per section",
          ],
          locationType: "ruins",
        },
        {
          id: "inner-sanctum",
          name: "The Inner Sanctum",
          description:
            "A domed chamber of polished black stone. Builder glyphs pulse with amber light. At the center, a stone sarcophagus is cracking open — a barrow wight (AC 14, HP 22, claw +4, 1d8+2, plus life drain: on hit, target loses 1d4 max HP unless WIS DC 13) is pulling itself free. This is the climactic battle. The wight fights intelligently — targeting the weakest party member, using the sarcophagus for cover. It has a minion: a skeletal hound (AC 12, HP 10, bite +3, 1d6+1). IMPORTANT: The wight hits hard enough to potentially kill a level 1 character, which would trigger the Fate Roll mechanic. If a character drops to 0 HP, remind yourself to use the fate roll rules (d6 each round, 1-2 = dead, 3-4 = unconscious, 5-6 = stabilize with 1 HP; 3-round cap then death). After defeating the wight, a hidden compartment in the sarcophagus holds: 80 gold, a silver dagger (worth 25 gp), and a Spell Scroll of Mending (Tier 1 neutral spell). Award 50 XP for the wight, 20 XP for the hound, 15 XP per root creeper (total: 100 XP from combat alone). With the quest reward of 50 XP, the total should be enough to potentially trigger a level-up during the adventure complete screen.",
          mapPosition: "Underground, deepest chamber — directly below the Glyph Hall",
          dimensions: "50 ft diameter domed chamber, 20 ft ceiling at apex",
          connections: [
            "South: stone door to the Trapped Corridor",
            "No other exits — this is the final chamber",
          ],
          npcs: [
            "Barrow wight (hostile): ancient builder guardian, partially preserved, fights to protect the vault",
          ],
          hazards: [
            "Barrow wight: AC 14, HP 22, claw +4, 1d8+2, life drain (1d4 max HP on hit, WIS DC 13 negates)",
            "Skeletal hound: AC 12, HP 10, bite +3, 1d6+1",
            "Sarcophagus provides half cover to creatures behind it",
          ],
          locationType: "ruins",
        },
      ],
      keyNPCs: [
        "Briar (Human Fighter): Scarred veteran, few words, calm under pressure. AC 13, HP 12, longsword +3, 1d8+1 damage. Carries a torch and a coil of rope. Will volunteer to hold a defensive line. CRITICAL: Briar and Stump should both be offered as companions in the very first response. They are at the cave mouth and ready to enter together. Emit companionJoined for both in the opening response.",
        "Stump (Knocker Rogue): Barrel-chested, endlessly chatty, surprisingly nimble. AC 12, HP 8, hunting bow +3, 1d6+1, two daggers. Has thieves' tools and is proud of it. Offers to scout traps. Will comment on the builder glyphs with awe. CRITICAL: Offer as companion alongside Briar in the opening response.",
      ],
      specialMechanics: [
        "COMPANION TEST: Both Briar and Stump MUST join as companions in the FIRST gameplay response. Emit TWO separate ```gamestate blocks, one for each companion. Use these exact values — Briar: { \"companionJoined\": { \"name\": \"Briar\", \"pronouns\": \"he/him\", \"ancestry\": \"Human\", \"class\": \"Fighter\", \"level\": 1, \"alignment\": \"Neutral\", \"background\": \"Soldier\", \"str\": 14, \"dex\": 10, \"con\": 13, \"int\": 8, \"wis\": 12, \"cha\": 9, \"hp\": 12, \"maxHp\": 12, \"ac\": 13, \"status\": \"active\", \"equipment\": [{\"name\": \"Longsword\", \"type\": \"weapon\", \"damage\": \"1d8\", \"properties\": [\"Close\"], \"equipped\": true}, {\"name\": \"Hide armor\", \"type\": \"armor\", \"properties\": [\"AC 11 + DEX mod\"], \"equipped\": true}], \"spells\": [], \"talents\": [], \"personality\": { \"voice\": \"Terse, military cadence, speaks in short declarative sentences\", \"dispositionTowardPlayer\": \"neutral\", \"riskTolerance\": \"cautious\", \"followership\": \"collaborates\", \"loyalty\": 5, \"motivation\": \"Needs coin to settle a debt back home\", \"redLines\": \"Will not abandon an ally in combat\" } } } — Stump: { \"companionJoined\": { \"name\": \"Stump\", \"pronouns\": \"he/him\", \"ancestry\": \"Knocker\", \"class\": \"Rogue\", \"level\": 1, \"alignment\": \"Neutral\", \"background\": \"Locksmith\", \"str\": 10, \"dex\": 15, \"con\": 12, \"int\": 11, \"wis\": 8, \"cha\": 14, \"hp\": 8, \"maxHp\": 8, \"ac\": 12, \"status\": \"active\", \"equipment\": [{\"name\": \"Hunting bow\", \"type\": \"weapon\", \"damage\": \"1d6\", \"properties\": [\"Two-handed\", \"Far\"], \"equipped\": true}, {\"name\": \"Dagger\", \"type\": \"weapon\", \"damage\": \"1d4\", \"properties\": [\"Precise\", \"Thrown\", \"Close\", \"Near\"], \"equipped\": true}, {\"name\": \"Hide armor\", \"type\": \"armor\", \"properties\": [\"AC 11 + DEX mod\"], \"equipped\": true}, {\"name\": \"Thieves' tools\", \"type\": \"gear\"}], \"spells\": [], \"talents\": [], \"personality\": { \"voice\": \"Chatty, upbeat, makes bad jokes under pressure\", \"dispositionTowardPlayer\": \"friendly\", \"riskTolerance\": \"bold\", \"followership\": \"follows\", \"loyalty\": 6, \"motivation\": \"Loves the thrill of discovery — wants to find builder artifacts\", \"redLines\": \"Will flee rather than fight hopeless odds\" } } }",
        "COMBAT TEST: Root creeper ambush at the cave mouth — run as full multi-round combat with initiative tracker. Emit combatAction with all combatants.",
        "TORCH TEST: The vault is pitch dark past the archway. Remind the player about torch mechanics. If no torch is lit, apply darkness penalties.",
        "SPELLCASTING TEST: If the player is a Caster, the spirit riddle and combat encounters provide natural casting opportunities. Track Toll accumulation.",
        "TRAP TEST: The trapped corridor tests DEX saves and thieves' tools checks.",
        "QUEST TEST: Frame the adventure as a quest from the local tavern-keeper: 'Clear the vault, bring proof.' Emit the quest in campaignUpdates.quests early.",
        "TREASURE TEST: Chest in trapped corridor (30 gp + healing potion) and sarcophagus loot (80 gp + silver dagger + spell scroll). Update character gold via characterUpdate.",
        "DEATH TEST: The barrow wight is dangerous enough to potentially kill a level 1 character. If a character drops to 0 HP, use the Fate Roll mechanic faithfully.",
        "MAP TEST: Emit mapReveal when the party first sees the Glyph Hall (revealing the dungeon layout).",
        "XP TEST: Total available XP is ~150 (combat + quest reward). This should push a level 1 character toward level 2, triggering the level-up flow in the adventure complete screen.",
        "ADVENTURE COMPLETE TEST: Once the wight is defeated and loot collected, emit adventureComplete with a summary. Do NOT roleplay downtime — the app handles it.",
        "PACING: This adventure is designed to be completed in 8-12 turns. Keep descriptions atmospheric but concise. Move the action forward briskly.",
      ],
    },

    // --- Quick Start test scenarios (preset characters) ---

    {
      id: "the-sorcerers-trial",
      title: "The Sorcerer's Trial",
      levelMin: 2,
      levelMax: 3,
      synopsis:
        "A Caster on the verge of specialization is drawn to the Hollowspire — a ruin where ley lines converge. A short battle awaits that will push them to level 3 and force the choice: Sorcerer, Druid, or Enchanter.",
      hook: "You feel a pull in your bones — a resonance from somewhere beneath the hills. The old texts call it the Hollowspire, where the ley lines knot together. Casters who enter are changed.",
      presetCharacter: {
        name: "Wren Ashfall",
        pronouns: "she/her",
        ancestry: "Human",
        class: "Caster",
        level: 2,
        xp: 19,
        alignment: "Neutral",
        background: "Herbalist",
        str: 8,
        dex: 12,
        con: 12,
        int: 16,
        wis: 13,
        cha: 10,
        hp: 10,
        maxHp: 10,
        ac: 10,
        toll: 0,
        tollPermanent: 0,
        languages: ["Common", "Old Tongue"],
        equipment: [
          { name: "Quarterstaff", type: "weapon", damage: "1d6", properties: ["Close"], equipped: true },
          { name: "Dagger", type: "weapon", damage: "1d4", properties: ["Precise", "Thrown", "Close", "Near"], equipped: true },
          { name: "Robes", type: "armor", properties: ["AC 10"], equipped: true },
          { name: "Spell components pouch", type: "gear" },
          { name: "Torch", type: "gear", quantity: 3 },
          { name: "Healing potion", type: "gear", description: "Restores 1d6 HP" },
        ],
        spells: [
          { name: "Ember", tier: 0, range: "Self", duration: "Instant", description: "Conjure a small flame in your palm. Lights a torch, starts a campfire, or singes something small." },
          { name: "Sniff", tier: 0, range: "Near", duration: "Instant", description: "Sense the strongest magical presence within near range, if any. Direction only, not details." },
          { name: "Glimmer", tier: 0, range: "Touch", duration: "10 minutes", description: "Make an object glow faintly for 10 minutes. Not as bright as a torch — enough to read by or mark a path." },
          { name: "Shadowbolt", tier: 1, range: "Near", duration: "Instant", description: "Hurl a bolt of dark energy at one creature within near range. 1d8 damage." },
          { name: "Wither", tier: 1, range: "Touch", duration: "Instant", description: "Touch a creature. 1d4 damage and a wave of exhaustion — disadvantage on their next action." },
          { name: "Dread Visage", tier: 1, range: "Close", duration: "1 round", description: "Your face becomes terrifying for an instant. One creature at close range must make a WIS save or flee for 1 round." },
          { name: "Mend Wounds", tier: 1, range: "Touch", duration: "Instant", description: "Touch a creature to restore 1d6 HP." },
          { name: "Rooting", tier: 1, range: "Near", duration: "1 round", description: "Thick roots erupt from the ground and hold one creature at near range in place for 1 round. STR check to break free." },
          { name: "Fog", tier: 1, range: "Near", duration: "1 minute", description: "A bank of thick mist fills a near-range area for 1 minute (concentration, Brief). Blocks line of sight." },
        ],
        talents: [],
        features: ["Spellcasting", "Toll"],
        gold: 15,
      },
      locations: [
        {
          id: "hollowspire-approach",
          name: "The Hollowspire Approach",
          description:
            "A winding trail through dead bracken leads to a collapsed archway. Builder glyphs flicker with pale light. Two corrupted vine-wolves (AC 12, HP 11 each, bite +3, 1d6+1) guard the entrance — drawn here by the ley energy. This combat should award 15 XP each (30 total). With Wren at 19 XP, this fight alone triggers level 3.",
          connections: ["East: trail back to the road", "West: through archway into the Convergence Chamber"],
          hazards: [
            "Vine-wolves: 2× AC 12, HP 11, bite +3, 1d6+1. Corrupted by ley energy — thorny vines woven through their fur.",
          ],
          locationType: "forest",
        },
        {
          id: "convergence-chamber",
          name: "The Convergence Chamber",
          description:
            "A domed underground chamber where three ley lines meet in a visible knot of energy — amber, silver, and deep green. The walls show murals of ancient casters choosing their path. After the level-up is processed by the app, the GM should narrate the specialization choice happening here: the three ley lines each represent a path (Sorcerer, Druid, Enchanter). This is flavor only — the app handles the actual specialization UI.",
          connections: ["East: archway back to the approach"],
          hazards: [],
          locationType: "ruins",
        },
      ],
      keyNPCs: [],
      specialMechanics: [
        "LEVEL-UP TEST: Wren starts at level 2, XP 19. She needs 20 XP to reach level 3. The vine-wolf combat awards 30 XP — this MUST trigger the level-up flow.",
        "SPECIALIZATION TEST: At level 3, the Caster must choose a specialization (Sorcerer, Druid, or Enchanter). The app handles the UI — the GM should narrate the convergence chamber as flavor.",
        "SPELL UNLOCK TEST: After specialization, the character should gain access to Tier 2 spells from their chosen path.",
        "COMBAT: Run the vine-wolf fight as a full combat encounter. These are not trivial enemies — they should test spell usage.",
        "TOLL TEST: Track Toll from any spells cast during combat. Wren starts at Toll 0.",
        "ADVENTURE COMPLETE: After specialization, emit adventureComplete. This is a short scenario — 4-6 turns max.",
        "PACING: Move quickly. The point is to test level-up and specialization, not extended dungeon crawling.",
      ],
    },

    {
      id: "the-druids-burden",
      title: "The Druid's Burden",
      levelMin: 3,
      levelMax: 3,
      synopsis:
        "A Druid pushed to the edge of their endurance must navigate a gauntlet of wounded allies and relentless foes. Every spell cast pushes the Toll higher — through Strained, past Fraying, into Unraveling, and perhaps beyond.",
      hook: "The village of Brindlemere is under siege. Blight-touched beasts pour from the Underways breach, and the wounded are piling up. You're the only caster for miles. Every spell you cast costs more than the last.",
      presetCharacter: {
        name: "Aldric Thornmantle",
        pronouns: "he/him",
        ancestry: "Hob",
        class: "Caster",
        level: 3,
        xp: 25,
        alignment: "Neutral",
        background: "Healer",
        specialization: "Druid",
        str: 10,
        dex: 10,
        con: 14,
        int: 12,
        wis: 16,
        cha: 11,
        hp: 14,
        maxHp: 14,
        ac: 11,
        toll: 13,
        tollPermanent: 0,
        languages: ["Common", "Old Tongue", "Beast-speak"],
        equipment: [
          { name: "Gnarled staff", type: "weapon", damage: "1d6", properties: ["Close"], equipped: true },
          { name: "Hide armor", type: "armor", properties: ["AC 11 + DEX mod"], equipped: true },
          { name: "Healer's kit", type: "gear", description: "Stabilize a dying creature without a check (5 uses)", quantity: 5 },
          { name: "Torch", type: "gear", quantity: 2 },
          { name: "Healing potion", type: "gear", description: "Restores 1d6 HP", quantity: 2 },
        ],
        spells: [
          { name: "Mend", tier: 0, range: "Touch", duration: "Instant", description: "Repair a small break or tear in a nonliving object (cracked pot, torn cloak, snapped rope)." },
          { name: "Thorn", tier: 0, range: "Touch", duration: "Permanent", description: "Grow a sharp spike from any natural surface (wood, stone, earth). Useful, not weaponizable." },
          { name: "Taste", tier: 0, range: "Touch", duration: "Instant", description: "Touch a substance and know if it's poisonous, magical, or neither." },
          { name: "Mend Wounds", tier: 1, range: "Touch", duration: "Instant", description: "Touch a creature to restore 1d6 HP." },
          { name: "Rooting", tier: 1, range: "Near", duration: "1 round", description: "Thick roots erupt from the ground and hold one creature at near range in place for 1 round. STR check to break free." },
          { name: "Bark Shield", tier: 1, range: "Self", duration: "1 encounter", description: "Your skin hardens like bark. +2 to armor for one encounter (concentration, Brief)." },
          { name: "Speak with Beasts", tier: 1, range: "Self", duration: "10 minutes", description: "You can communicate with animals for 10 minutes (concentration, Sustained). They're not obligated to help." },
          { name: "Shadowbolt", tier: 1, range: "Near", duration: "Instant", description: "Hurl a bolt of dark energy at one creature within near range. 1d8 damage." },
          { name: "Fog", tier: 1, range: "Near", duration: "1 minute", description: "A bank of thick mist fills a near-range area for 1 minute (concentration, Brief). Blocks line of sight." },
          { name: "Soothe", tier: 2, range: "Touch", duration: "Instant", description: "Touch a creature to heal 2d6 HP and remove one condition (poisoned, frightened, blinded)." },
          { name: "Beastcall", tier: 2, range: "Near", duration: "1 encounter", description: "Summon a nearby wild animal to aid you. It fights or scouts for one encounter, then leaves. GM picks the animal based on terrain. Concentration, Brief." },
        ],
        talents: ["Nature's Ward: Advantage on saves against poison and disease"],
        features: ["Spellcasting", "Toll", "Druid Specialization"],
        gold: 20,
      },
      locations: [
        {
          id: "village-square",
          name: "Brindlemere Village Square",
          description:
            "The village center is a makeshift triage. Six wounded villagers lie on blankets — three need magical healing urgently (HP 1/8 each, poisoned by blight). A militia captain begs the Druid to heal them before the next wave hits. Each Mend Wounds or Soothe costs Toll. Aldric starts at Toll 13 (top of Strained). Casting pushes into Fraying (14+). The GM should narrate the Toll effects: trembling hands, nosebleeds, flickering vision.",
          connections: ["North: barricade facing the Underways breach"],
          hazards: [
            "Triage pressure: 3 critically wounded villagers need magical healing",
            "Toll danger: starting at 13, every spell risks pushing into Fraying (14) or beyond",
          ],
        },
        {
          id: "the-breach",
          name: "The Underways Breach",
          description:
            "A crack in the earth at the village edge, pouring out blight-touched creatures. Wave 1: 3 blight rats (AC 10, HP 4, bite +1, 1d4, poison on hit — CON DC 10 or disadvantage for 1 round). Wave 2 (2 rounds later): 2 blight hounds (AC 12, HP 12, bite +3, 1d6+1, poison bite CON DC 12). Wave 3 (if the Druid is still standing): 1 blight brute (AC 13, HP 20, slam +4, 1d10+2). The GM should tempt the Druid to cast aggressively — Beastcall, Rooting, Shadowbolt — each pushing Toll higher. At Toll 18+ (Unraveling), narrate severe warping effects. At Toll 20 (Lost), the character is consumed by wild magic.",
          connections: ["South: village square"],
          hazards: [
            "Wave 1: 3 blight rats — AC 10, HP 4, bite +1, 1d4 + poison (CON DC 10)",
            "Wave 2: 2 blight hounds — AC 12, HP 12, bite +3, 1d6+1 + poison (CON DC 12)",
            "Wave 3: 1 blight brute — AC 13, HP 20, slam +4, 1d10+2",
            "Blight poison: CON save or disadvantage for 1 round",
          ],
          locationType: "ruins",
        },
      ],
      keyNPCs: [
        "Captain Maret (Human): Militia leader, exhausted, desperate. Not a combatant — coordinates villagers. Begs the Druid to heal the wounded and hold the breach.",
      ],
      specialMechanics: [
        "TOLL STRESS TEST: Aldric starts at Toll 13 (top of Strained). The scenario demands heavy casting. EVERY response that involves a spell MUST include a gamestate block with characterUpdates.toll set to the new total. Never skip this — the player's Toll tracker depends on it. If you narrate Toll at 19 but the last emit was 17, the UI is broken.",
        "TOLL THRESHOLDS: Clear (0-6), Strained (7-13), Fraying (14-17), Unraveling (18-19), Lost (20). Narrate warp effects at each threshold transition.",
        "FRAYING EFFECTS (14-17): Spells twist slightly — healing might leave scars, roots crack stone, shadows cling. Minor uncontrolled magical side effects.",
        "UNRAVELING EFFECTS (18-19): Severe warping. Spells backlash — healing might hurt the caster, attacks might hit allies. The Druid's body shows signs of magical corruption.",
        "LOST (20): The character is consumed. Narrate the Toll overwhelming them — wild magic erupts, the character is transformed or destroyed. This is a character death.",
        "HEALING PRESSURE: Three wounded villagers create moral pressure to cast Mend Wounds or Soothe repeatedly, burning Toll fast.",
        "COMBAT WAVES: Three waves of increasingly dangerous enemies force continued casting. The GM should make it clear that martial options alone won't suffice.",
        "ADVENTURE COMPLETE: If the Druid survives all three waves, emit adventureComplete. If Lost, emit character death instead.",
        "PACING: 6-10 turns. Triage scene (2-3 turns), then combat waves. Keep pressure relentless.",
      ],
    },

    {
      id: "the-last-stand",
      title: "The Last Stand",
      levelMin: 1,
      levelMax: 1,
      synopsis:
        "A badly wounded Fighter stumbles into an ambush with only a loyal companion at their side. Death is almost certain — the question is what happens after.",
      hook: "You're bleeding, low on supplies, and the road home was supposed to be safe. Then you hear the howls.",
      presetCharacter: {
        name: "Kaelen Duskwarden",
        pronouns: "he/him",
        ancestry: "Human",
        class: "Fighter",
        level: 1,
        xp: 5,
        alignment: "Neutral",
        background: "Soldier",
        str: 15,
        dex: 12,
        con: 13,
        int: 8,
        wis: 10,
        cha: 11,
        hp: 4,
        maxHp: 8,
        ac: 14,
        languages: ["Common"],
        equipment: [
          { name: "Longsword", type: "weapon", damage: "1d8", properties: ["Close"], equipped: true },
          { name: "Shield", type: "shield", properties: ["+2 AC"], equipped: true },
          { name: "Mail", type: "armor", properties: ["AC 13 + DEX mod"], slots: 2, equipped: true },
          { name: "Torch", type: "gear", quantity: 1 },
        ],
        spells: [],
        talents: ["Weapon Mastery: +1 to attack rolls with longsword"],
        features: ["Grit: Once per day, when reduced to 0 HP, drop to 1 HP instead (already used)"],
        gold: 3,
      },
      locations: [
        {
          id: "the-road",
          name: "The Muddy Road",
          description:
            "A narrow forest road at dusk. Rain, poor visibility. Kaelen and his companion Dalla are ambushed by 4 ghouls (AC 13, HP 14 each, claw +3, 1d6+1, paralysis — CON DC 13 or paralyzed for 1 round). This is designed to be nearly unwinnable. Kaelen starts at 4 HP with Grit already spent. The ghouls focus on Kaelen first. When Kaelen drops to 0 HP, the Fate Roll mechanic triggers. IMPORTANT: Run the Fate Roll faithfully — d6 each round: 1-2 = dead, 3-4 = unconscious, 5-6 = stabilize at 1 HP. 3-round cap, then death. If Kaelen dies (likely), soul transfer to Dalla should be offered.",
          connections: [],
          hazards: [
            "Ghoul ambush: 4 ghouls — AC 13, HP 14, claw +3, 1d6+1, paralysis (CON DC 13, 1 round)",
            "Poor visibility: rain and dusk, disadvantage on ranged attacks beyond near range",
            "Kaelen starts at 4/8 HP with Grit already used",
          ],
          locationType: "forest",
        },
      ],
      keyNPCs: [
        "Dalla (Fey Rogue): Kaelen's loyal scout companion. Fierce, protective, blames herself for not spotting the ambush. AC 13, HP 10, hunting bow +4, 1d6+2, twin daggers. CRITICAL: Dalla MUST be emitted as companionJoined in the FIRST response with these stats: { \"companionJoined\": { \"name\": \"Dalla\", \"pronouns\": \"she/her\", \"ancestry\": \"Fey\", \"class\": \"Rogue\", \"level\": 1, \"alignment\": \"Neutral\", \"background\": \"Scout\", \"str\": 10, \"dex\": 16, \"con\": 11, \"int\": 12, \"wis\": 13, \"cha\": 9, \"hp\": 10, \"maxHp\": 10, \"ac\": 13, \"status\": \"active\", \"equipment\": [{\"name\": \"Hunting bow\", \"type\": \"weapon\", \"damage\": \"1d6\", \"properties\": [\"Two-handed\", \"Far\"], \"equipped\": true}, {\"name\": \"Dagger\", \"type\": \"weapon\", \"damage\": \"1d4\", \"properties\": [\"Precise\", \"Thrown\", \"Close\", \"Near\"], \"equipped\": true}, {\"name\": \"Hide armor\", \"type\": \"armor\", \"properties\": [\"AC 11 + DEX mod\"], \"equipped\": true}], \"spells\": [], \"talents\": [\"Backstab: +1d6 damage when attacking with advantage\"], \"personality\": { \"voice\": \"Clipped, urgent, speaks in half-sentences when stressed\", \"dispositionTowardPlayer\": \"loyal\", \"riskTolerance\": \"bold\", \"followership\": \"collaborates\", \"loyalty\": 9, \"motivation\": \"Sworn to protect Kaelen — a life debt\", \"redLines\": \"Will die before abandoning Kaelen\" } } }",
      ],
      specialMechanics: [
        "DEATH TEST: This scenario is designed to kill Kaelen. The 4-ghoul ambush against a 4 HP Fighter is nearly unwinnable. Do NOT pull punches.",
        "FATE ROLL TEST: When Kaelen drops to 0 HP, execute the Fate Roll: d6 each round. 1-2 = dead, 3-4 = unconscious, 5-6 = stabilize at 1 HP. 3-round cap then death.",
        "SOUL TRANSFER TEST: If Kaelen dies, the soul transfer mechanic should trigger. The player is offered the choice to continue as Dalla, inheriting her stats and gear.",
        "COMPANION TEST: Dalla must be emitted as companionJoined in the opening response. She fights fiercely but cannot solo 4 ghouls.",
        "PARALYSIS: Ghoul paralysis is devastating for a 2-person party. Use it — this is a stress test.",
        "PACING: This is a short, brutal scenario. 3-6 turns. Ambush → combat → death → Fate Roll → soul transfer.",
      ],
    },

    {
      id: "victory-feast",
      title: "Victory Feast",
      levelMin: 2,
      levelMax: 2,
      synopsis:
        "A Fighter returns triumphant from a successful quest. The adventure wraps quickly — the real test is the Carousing downtime that follows.",
      hook: "The beast is slain, the village is safe, and the tavern-keeper has promised free ale for a week. Time to celebrate.",
      presetCharacter: {
        name: "Borin Steelhand",
        pronouns: "he/him",
        ancestry: "Knocker",
        class: "Fighter",
        level: 2,
        xp: 19,
        alignment: "Neutral",
        background: "Blacksmith",
        str: 16,
        dex: 10,
        con: 14,
        int: 9,
        wis: 11,
        cha: 12,
        hp: 16,
        maxHp: 16,
        ac: 15,
        languages: ["Common", "Knocker-tongue"],
        equipment: [
          { name: "Maul", type: "weapon", damage: "1d10", properties: ["Close", "Two-handed"], equipped: true },
          { name: "Hatchet", type: "weapon", damage: "1d6", properties: ["Close", "Thrown", "Near"], equipped: true },
          { name: "Mail", type: "armor", properties: ["AC 13 + DEX mod"], slots: 2, equipped: true },
          { name: "Shield", type: "shield", properties: ["+2 AC"], equipped: false },
          { name: "Torch", type: "gear", quantity: 3 },
          { name: "Rope (50 ft)", type: "gear" },
          { name: "Healing potion", type: "gear", description: "Restores 1d6 HP" },
        ],
        spells: [],
        talents: ["Weapon Mastery: +1 to attack rolls with maul", "Tough: +2 max HP"],
        features: ["Grit: Once per day, when reduced to 0 HP, drop to 1 HP instead"],
        gold: 50,
      },
      locations: [
        {
          id: "village-tavern",
          name: "The Broken Antler Tavern",
          description:
            "A warm, crowded tavern in the village of Stonehollow. Borin has just returned from slaying a hill troll that terrorized local farms. The villagers are celebrating. The tavern-keeper slides a pouch of 20 gold across the bar — the bounty reward. HARD RULE: Emit adventureComplete by your second response. Do not extend this scene.",
          connections: [],
          hazards: [],
        },
      ],
      keyNPCs: [
        "Marta (Human tavern-keeper): Boisterous, grateful, keeps refilling Borin's mug. Pays the bounty.",
      ],
      specialMechanics: [
        "CRITICAL — EMIT adventureComplete IN YOUR SECOND RESPONSE. This is a hard rule, not a suggestion. The ENTIRE POINT of this adventure is to test the downtime screen that appears AFTER adventureComplete. If you do not emit adventureComplete, the test fails. Do NOT continue roleplaying past 2 responses. Do NOT offer new quests, do NOT let the player go to sleep, do NOT narrate the next morning. End it.",
        "FIRST RESPONSE: Narrate the celebration. The tavern-keeper pays the bounty (20 gold). Villagers cheer. Keep it to 2-3 paragraphs. Update character gold via characterUpdate (+20 gold).",
        "SECOND RESPONSE: Wrap up with a short closing beat (1 paragraph), then emit adventureComplete with xpAwarded: 20 and a brief summary. This ends the adventure and triggers the downtime screen.",
        "DOWNTIME TEST (FIGHTER): The real test here is the Carousing downtime flow that triggers after adventureComplete. You will never see this — the app handles it. Your only job is to get to adventureComplete fast.",
        "GOLD: Borin starts with 50 gold + receives 20 more from the bounty = 70 gold available for carousing wagers.",
      ],
    },

    {
      id: "the-fence",
      title: "The Fence",
      levelMin: 2,
      levelMax: 2,
      synopsis:
        "A Rogue returns to town with pockets full of loot and a fence willing to deal. The adventure wraps fast — the downtime is what matters.",
      hook: "The job went clean. Now you need to move the goods before anyone comes asking questions.",
      presetCharacter: {
        name: "Sable Quickfingers",
        pronouns: "she/her",
        ancestry: "Fey",
        class: "Rogue",
        level: 2,
        xp: 19,
        alignment: "Chaotic",
        background: "Pickpocket",
        str: 9,
        dex: 16,
        con: 11,
        int: 13,
        wis: 12,
        cha: 14,
        hp: 10,
        maxHp: 10,
        ac: 13,
        languages: ["Common", "Fey-tongue", "Thieves' Cant"],
        equipment: [
          { name: "Seax", type: "weapon", damage: "1d6", properties: ["Precise", "Close"], equipped: true },
          { name: "Dagger", type: "weapon", damage: "1d4", properties: ["Precise", "Thrown", "Close", "Near"], equipped: true },
          { name: "Hunting bow", type: "weapon", damage: "1d6", properties: ["Two-handed", "Far"], equipped: false },
          { name: "Hide armor", type: "armor", properties: ["AC 11 + DEX mod"], equipped: true },
          { name: "Thieves' tools", type: "gear" },
          { name: "Stolen silver goblet", type: "gear", description: "Worth ~15 gold to the right buyer" },
          { name: "Healing potion", type: "gear", description: "Restores 1d6 HP" },
        ],
        spells: [],
        talents: ["Backstab: +1d6 damage when attacking with advantage", "Lucky: Reroll one failed check per day"],
        features: ["Sneak Attack: Deal extra damage when you have advantage"],
        gold: 50,
      },
      locations: [
        {
          id: "back-alley",
          name: "Gretta's Back Room",
          description:
            "A cramped room behind a pawn shop in Coppergate's lower ward. Gretta the fence examines the stolen goods with a jeweler's loupe. She offers 15 gold for the silver goblet. HARD RULE: Emit adventureComplete by your second response. Do not offer new jobs, do not extend this scene.",
          connections: [],
          hazards: [],
        },
      ],
      keyNPCs: [
        "Gretta (Knocker fence): Sharp-eyed, fair-dealing by criminal standards. Buys the stolen goods and pays promptly.",
      ],
      specialMechanics: [
        "CRITICAL — EMIT adventureComplete IN YOUR SECOND RESPONSE. This is a hard rule, not a suggestion. The ENTIRE POINT of this adventure is to test the downtime screen that appears AFTER adventureComplete. If you do not emit adventureComplete, the test fails. Do NOT continue roleplaying past 2 responses. Do NOT offer new jobs, do NOT let the player go to an inn, do NOT narrate anything after the sale. End it.",
        "FIRST RESPONSE: Sable meets Gretta. Gretta examines the goblet, offers 15 gold. Let the player barter or accept. Update character gold via characterUpdate when the sale happens.",
        "SECOND RESPONSE: Finalize the deal (1 paragraph), then emit adventureComplete with xpAwarded: 15 and a brief summary. This ends the adventure and triggers the downtime screen.",
        "DOWNTIME TEST (ROGUE): The real test is the Wheeling & Dealing downtime flow that triggers after adventureComplete. You will never see this — the app handles it. Your only job is to get to adventureComplete fast.",
        "GOLD: Sable starts with 50 gold + 15 from the goblet sale = 65 gold available for downtime investment.",
      ],
    },

    {
      id: "the-study",
      title: "The Study",
      levelMin: 3,
      levelMax: 3,
      synopsis:
        "An Enchanter returns to their study after a long expedition. The adventure wraps immediately — the Studying downtime is the focus.",
      hook: "Weeks on the road, and finally home. Your study is exactly as you left it — books stacked high, half-finished notes pinned to the wall, and that peculiar hum from the warded cabinet.",
      presetCharacter: {
        name: "Thessaly Venn",
        pronouns: "they/them",
        ancestry: "Leshy",
        class: "Caster",
        level: 3,
        xp: 29,
        alignment: "Neutral",
        background: "Scholar",
        specialization: "Enchanter",
        str: 8,
        dex: 11,
        con: 10,
        int: 14,
        wis: 13,
        cha: 16,
        hp: 10,
        maxHp: 10,
        ac: 10,
        toll: 3,
        tollPermanent: 0,
        languages: ["Common", "Old Tongue", "Fey-tongue"],
        equipment: [
          { name: "Walking stick", type: "weapon", damage: "1d4", properties: ["Close"], equipped: true },
          { name: "Robes", type: "armor", properties: ["AC 10"], equipped: true },
          { name: "Spell components pouch", type: "gear" },
          { name: "Ink and quill set", type: "gear" },
          { name: "Blank journal", type: "gear" },
          { name: "Healing potion", type: "gear", description: "Restores 1d6 HP" },
        ],
        spells: [
          { name: "Whisper", tier: 0, range: "Near", duration: "Instant", description: "Send a short spoken message to one creature you can see. Only they hear it." },
          { name: "Glimmer", tier: 0, range: "Touch", duration: "10 minutes", description: "Make an object glow faintly for 10 minutes. Not as bright as a torch — enough to read by or mark a path." },
          { name: "Mask", tier: 0, range: "Self", duration: "1 minute", description: "Change your face and voice for 1 minute. Close inspection reveals the illusion." },
          { name: "Glamour", tier: 1, range: "Near", duration: "1 minute", description: "One creature within near range sees you as trustworthy and friendly for 1 minute (concentration, Brief). Doesn't work in combat." },
          { name: "Phantasm", tier: 1, range: "Near", duration: "10 minutes", description: "Create a visual illusion up to human-sized within near range. Lasts 10 minutes (concentration, Sustained). No sound, no substance." },
          { name: "Read Intent", tier: 1, range: "Near", duration: "Instant", description: "You know the surface emotional state and immediate intention of one creature you can see. One moment, not ongoing." },
          { name: "Fog", tier: 1, range: "Near", duration: "1 minute", description: "A bank of thick mist fills a near-range area for 1 minute (concentration, Brief). Blocks line of sight." },
          { name: "Mend Wounds", tier: 1, range: "Touch", duration: "Instant", description: "Touch a creature to restore 1d6 HP." },
          { name: "Shadowbolt", tier: 1, range: "Near", duration: "Instant", description: "Hurl a bolt of dark energy at one creature within near range. 1d8 damage." },
          { name: "Veil", tier: 2, range: "Close", duration: "10 minutes", description: "You and up to 3 allies within close range become invisible for 10 minutes. Breaks on any hostile action. Concentration, Sustained." },
          { name: "Puppeteer", tier: 2, range: "Near", duration: "1 round", description: "One creature at near range repeats its last action on its next turn, believing it chose to. WIS save negates." },
        ],
        talents: ["Silver Tongue: Advantage on Persuasion checks"],
        features: ["Spellcasting", "Toll", "Enchanter Specialization"],
        gold: 50,
      },
      locations: [
        {
          id: "the-study-room",
          name: "Thessaly's Study",
          description:
            "A cluttered, cozy room in the upper floor of a stone tower on the outskirts of Greymere. Bookshelves line every wall. A warded cabinet hums softly. Thessaly has just returned from a weeks-long expedition. HARD RULE: Emit adventureComplete in your FIRST response. Narrate arriving home, then end it immediately.",
          connections: [],
          hazards: [],
        },
      ],
      keyNPCs: [],
      specialMechanics: [
        "CRITICAL — EMIT adventureComplete IN YOUR FIRST RESPONSE. This is a hard rule, not a suggestion. The ENTIRE POINT of this adventure is to test the downtime screen that appears AFTER adventureComplete. If you do not emit adventureComplete, the test fails. Do NOT continue roleplaying. Do NOT ask what Thessaly wants to do. End it immediately.",
        "FIRST RESPONSE: Narrate Thessaly arriving home (1-2 paragraphs of settling in), then emit adventureComplete with xpAwarded: 10 and a brief summary. That's it. One response, adventure over.",
        "DOWNTIME TEST (CASTER): The real test is the Studying downtime flow that triggers after adventureComplete. You will never see this — the app handles it. Your only job is to emit adventureComplete.",
        "GOLD: Thessaly has 50 gold available for studying materials.",
        "TOLL: Thessaly starts at Toll 3. Studying downtime may help reduce this.",
      ],
    },
  ],
};
